---
title: "lab4"
author: "Ryan Herren, Carter Meseck"
date: "3/19/2021"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
defense <- read_excel('/Users/ryanherren/Desktop/DS202/ds202_lab4/cyclonesFootball2020.xlsx', sheet='Defensive')
str(defense)

offense <- read_excel('/Users/ryanherren/Desktop/DS202/ds202_lab4/cyclonesFootball2020.xlsx', sheet='Offensive')
str(offense)

biography <- read_excel('/Users/ryanherren/Desktop/DS202/ds202_lab4/cyclonesFootball2020.xlsx', sheet='Biography')
str(biography)
```
## 1.1
```{r}
defClean <- defense
offClean <- offense
bioClean <- biography

defClean$Name <- as.factor(defClean$Name)
defClean$Opponent_Opponent <- as.factor(defClean$Opponent_Opponent)

offClean$Name <- as.factor(offClean$Name)
offClean$Opponent_Opponent <- as.factor(offClean$Opponent_Opponent)

bioClean$Name <- as.factor(bioClean$Name)

defClean <- defClean %>% mutate(across(where(is.character),as.numeric))

offClean <- offClean %>% mutate(across(where(is.character),as.numeric))

bioClean$Weight <- bioClean$Weight %>% as.numeric()
```
## 1.2
```{r}
defClean <- defense %>%
  mutate(Name = as.factor(Name),
         Opponent_Opponent = as.factor(Opponent_Opponent),
         Tackles_Solo = as.numeric(Tackles_Solo),
         Tackles_ASST = as.numeric(Tackles_ASST),
         Tackles_TFL = as.numeric(Tackles_TFL),
         Tackles_Sack = as.numeric(Tackles_Sack),
         Turnover_FF = as.numeric(Turnover_FF),
         Turnover_FR = as.numeric(Turnover_FR),
         Turnover_INT = as.numeric(Turnover_INT),
         Pass_QBH = as.numeric(Pass_QBH),
         Pass_PB = as.numeric(Pass_PB))
str(defClean)
```

```{r}
offClean <- offense %>%
  mutate(Name = as.factor(Name),
         Opponent_Opponent = as.factor(Opponent_Opponent),
         Rushing_ATT = as.numeric(Rushing_ATT),
         Rushing_YDS = as.numeric(Rushing_YDS),
         Rushing_TD = as.numeric(Rushing_TD),
         Receiving_REC = as.numeric(Receiving_REC),
         Receiving_YDS = as.numeric(Receiving_YDS),
         Receiving_TD = as.numeric(Receiving_TD),
         `Passing_CMP-ATT` = as.numeric(`Passing_CMP-ATT`),
         Passing_YDS = as.numeric(Passing_YDS),
         Passing_TD = as.numeric(Passing_TD),
         Passing_INT = as.numeric(Passing_INT))
str(offClean)
```
## 1.3
```{r}
bioClean <- biography %>%
  separate(Height, c('Feet', 'Inches'), '-', convert=TRUE) %>%
  mutate(Name = as.factor(Name),
         Position = as.factor(Position),
         Feet = as.numeric(Feet),
         Inches = as.numeric(Inches),
         Weight = as.numeric(Weight),
         Class = as.factor(Class),
         Hometown = as.factor(Hometown),
         Highschool = as.factor(Highschool))
str(bioClean)
```
## 2.1
```{r}
offClean <- offClean %>% 
  pivot_longer(cols = Receiving_REC:Passing_INT, names_to = "stat")
offClean
```
## 2.2
```{r}
ggplot(data = offClean, aes(value)) +
  geom_histogram(fill = "brown3", bins = 100) + 
  labs(title = "Distribution of Offensive Stats",
       y = "Count", x = "Value") + 
  facet_wrap(~ stat)
```

## 2.3

```{r}
q23 <- offClean %>%
         select(Opponent_Opponent, stat, value) %>%
         filter(Opponent_Opponent == 'Oklahoma' | Opponent_Opponent == 'Oregon', stat == 'Receiving_YDS') %>%
         ggplot(aes(x = value, y = Opponent_Opponent, color = Opponent_Opponent)) + geom_point(position = 'jitter')
q23 + labs(title = "Receiving Yards by Game", color = "Opponent", x = "Opponent", y = "Yards")
```

## 2.4
```{r}
bioClean <- bioClean %>%
  separate(Hometown, c('Hometown_city', 'Hometown_state'), sep = ', ')
bioClean
```

## 2.5
```{r}
bioClean %>%
  select(Hometown_state) %>%
  group_by(Hometown_state) %>%
  summarise(count = n())
```
## 3.1
```{r}
q31 = ggplot(bioClean, aes(Hometown_state)) + geom_bar(fill = "brown3")+ coord_flip() + theme(axis.text.x = element_text(angle = 90))
q31 + labs(y = "Count", x = "Home State")
```

```{r}
offState <- offClean %>%
      distinct(Name) %>%
      left_join(bioClean, by = c("Name" = "Name"))
offState %>%
      group_by(Hometown_state) %>% 
      summarize(Players = n()) %>%
      ggplot(aes(x = Hometown_state, weight = Players)) + geom_bar(fill = "brown3") + coord_flip() +
      ggtitle("Offense") + ylab("Number of Offense Players") + xlab("State")
defState <- defClean %>%
      distinct(Name) %>%
      left_join(bioClean, by = c("Name" = "Name"))
defState %>%
      group_by(Hometown_state) %>% 
      summarize(Players = n()) %>%
      ggplot(aes(x = Hometown_state, weight = Players)) + geom_bar(fill = "brown3") + coord_flip() +
      ggtitle("Defense") + ylab("Number of Defense Players") + xlab("State")
```


## 3.2
```{r}

```

## 3.3
```{r}

```

